theme: jekyll-theme-minimal
title: "How to Train Your Guide Dog: Wayfinding and Safe Navigation with Human-Robot Modeling"
description: "HRI2023 LBR"
description: "J. Taery Kim, Wenhao Yu, Jie Tan, Greg Turk,Sehoon Ha"
google_analytics: 'G-F1HQVFCDJL'
